-- Migration: Add missing tables (connections, meeting_requests)
-- Run this in the Supabase Dashboard > SQL Editor > New Query
-- Safe to re-run: uses IF NOT EXISTS throughout

-- ============================================================
-- connections
-- ============================================================
-- Stores connection requests between attendees.
-- id is a UUID generated by the app (gen_random_uuid()).
-- expires_at is set on pending requests (14-day expiry).
-- status values: pending | accepted | declined

CREATE TABLE IF NOT EXISTS connections (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  requester_id    UUID NOT NULL,
  recipient_id    UUID NOT NULL,
  status          TEXT NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending', 'accepted', 'declined')),
  expires_at      TIMESTAMP WITH TIME ZONE,
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_connections_requester ON connections(requester_id);
CREATE INDEX IF NOT EXISTS idx_connections_recipient ON connections(recipient_id);
CREATE INDEX IF NOT EXISTS idx_connections_status    ON connections(status);

-- ============================================================
-- meeting_requests
-- ============================================================
-- Stores meeting requests between attendees.
-- id uses a custom text format: mtg_<timestamp>_<random>
-- status values: pending | scheduled | declined | cancelled | completed
-- meeting_type:  video | coffee | conference | phone
-- proposed_times: JSONB array of ISO 8601 timestamp strings
-- reminders_sent: tracks whether reminder notifications were sent

CREATE TABLE IF NOT EXISTS meeting_requests (
  id               TEXT PRIMARY KEY,
  requester_id     UUID NOT NULL,
  recipient_id     UUID NOT NULL,
  status           TEXT NOT NULL DEFAULT 'pending'
                     CHECK (status IN ('pending', 'scheduled', 'declined', 'cancelled', 'completed')),
  meeting_type     TEXT NOT NULL
                     CHECK (meeting_type IN ('video', 'coffee', 'conference', 'phone')),
  duration         INTEGER NOT NULL,
  context_message  TEXT,
  proposed_times   JSONB NOT NULL DEFAULT '[]',
  accepted_time    TIMESTAMP WITH TIME ZONE,
  calendar_platform TEXT
                     CHECK (calendar_platform IN ('google', 'microsoft')),
  meeting_link     TEXT,
  calendar_event_id TEXT,
  reminders_sent   JSONB NOT NULL DEFAULT '{"day_before": false, "hour_before": false}',
  created_at       TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at       TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_meeting_requests_requester     ON meeting_requests(requester_id);
CREATE INDEX IF NOT EXISTS idx_meeting_requests_recipient     ON meeting_requests(recipient_id);
CREATE INDEX IF NOT EXISTS idx_meeting_requests_status        ON meeting_requests(status);
CREATE INDEX IF NOT EXISTS idx_meeting_requests_accepted_time ON meeting_requests(accepted_time);

-- ============================================================
-- Row Level Security
-- ============================================================
-- The app uses the service-role key (supabaseAdmin) for all queries,
-- which bypasses RLS. Enabling RLS without policies blocks direct
-- anon/authenticated access while leaving the service role unaffected.

ALTER TABLE connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE meeting_requests ENABLE ROW LEVEL SECURITY;
